# Long Short-Term Memory Layer Neural Network- Hochreiter 1997.
### Sentiment Analysis - Fake News Classifier
- By using LSTM Neural Network - predict whether the News is Fake or Not

In [1]:
#Lets import the libraries -
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Lets load the dataset -
df = pd.read_csv('C:/Users/om/Desktop/train.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [4]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
#Lets Drop Nan Values because we cannot fix/handele NaN Values with text data and we have many records (20800)-
df=df.dropna()

In [6]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [7]:
#Lets split the data in x & y Axis veriables -
x=df.drop('label',axis=1)
y=df['label']

In [8]:
#Lets set Vocabulary size randomly- Lets consider in our dictionary we have 5000 different words - you can take any -
voc_size=5000

In [9]:
#Onehot Representation, it will give you index number of words -
messages=x.copy()
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [10]:
#Lets reset the index -
messages.reset_index(inplace=True)

In [11]:
#Lets call by indexing -
messages['title'][0]
print(len(messages['title']))

18285


In [12]:
#Lets load the nltk library -
import nltk
nltk.download('punkit')
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
from nltk.corpus import stopwords
stopwords.words('english')

[nltk_data] Error loading punkit: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [13]:
#Lets Create corpus -
corpus = []
for i in range(0,18285):
    a1=nltk.word_tokenize(messages['title'][i])
    a1=' '.join(a1)
    corpus.append(a1)
corpus

['House Dem Aide : We Didn ’ t Even See Comey ’ s Letter Until Jason Chaffetz Tweeted It',
 'FLYNN : Hillary Clinton , Big Woman on Campus - Breitbart',
 'Why the Truth Might Get You Fired',
 '15 Civilians Killed In Single US Airstrike Have Been Identified',
 'Iranian woman jailed for fictional unpublished story about woman stoned to death for adultery',
 'Jackie Mason : Hollywood Would Love Trump if He Bombed North Korea over Lack of Trans Bathrooms ( Exclusive Video ) - Breitbart',
 'Benoît Hamon Wins French Socialist Party ’ s Presidential Nomination - The New York Times',
 'A Back-Channel Plan for Ukraine and Russia , Courtesy of Trump Associates - The New York Times',
 'Obama ’ s Organizing for Action Partners with Soros-Linked ‘ Indivisible ’ to Disrupt Trump ’ s Agenda',
 "BBC Comedy Sketch `` Real Housewives of ISIS '' Causes Outrage",
 'Russian Researchers Discover Secret Nazi Military Base ‘ Treasure Hunter ’ in the Arctic [ Photos ]',
 'US Officials See No Link Between Trump

In [14]:
#Lets do the Text preprocessing -
import re
review = []
for i in range(len(corpus)):
    a2=re.sub('[^ a-zA-Z]',' ',corpus[i]).lower().split()
    a3=[lemmatizer.lemmatize(i) for i in a2 if not i in stopwords.words('english')]
    a3=' '.join(a3)
    review.append(a3)
review

['house dem aide even see comey letter jason chaffetz tweeted',
 'flynn hillary clinton big woman campus breitbart',
 'truth might get fired',
 'civilian killed single u airstrike identified',
 'iranian woman jailed fictional unpublished story woman stoned death adultery',
 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'beno hamon win french socialist party presidential nomination new york time',
 'back channel plan ukraine russia courtesy trump associate new york time',
 'obama organizing action partner soros linked indivisible disrupt trump agenda',
 'bbc comedy sketch real housewife isi cause outrage',
 'russian researcher discover secret nazi military base treasure hunter arctic photo',
 'u official see link trump russia',
 'yes paid government troll social medium blog forum website',
 'major league soccer argentine find home success new york time',
 'well fargo chief abruptly step new york time',
 'anonymous donor pay 

In [15]:
#Lets take a look on changes we made -
print(len(review))
print(messages['title'][0])
print(review[0])

18285
House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It
house dem aide even see comey letter jason chaffetz tweeted


In [16]:
#Lets do Word Embedding i.e- One Hot Encoding to convert Words into Vectors-
from tensorflow.keras.preprocessing.text import one_hot
onehot_repr=[one_hot(words,voc_size)for words in review] 
onehot_repr

[[1734, 3968, 3661, 1973, 4080, 3769, 1682, 3804, 3129, 3901],
 [1086, 3601, 2806, 4745, 1311, 1573, 2643],
 [1206, 2555, 3668, 848],
 [4693, 344, 3596, 1549, 4818, 2786],
 [2733, 1311, 395, 4825, 4353, 4064, 1311, 1190, 4019, 505],
 [1461,
  3781,
  1636,
  2682,
  1792,
  4016,
  16,
  3402,
  4980,
  2272,
  398,
  917,
  2353,
  4723,
  2643],
 [1347, 268, 2637, 3439, 108, 2680, 3286, 2465, 1061, 602, 965],
 [2966, 1100, 2131, 1813, 4254, 4911, 4016, 457, 1061, 602, 965],
 [1667, 892, 2077, 1782, 1678, 672, 2611, 4084, 4016, 1725],
 [3783, 1036, 2575, 4342, 1625, 4996, 2112, 2587],
 [1436, 4938, 3053, 2947, 4484, 4500, 1907, 3861, 2551, 3775, 3845],
 [1549, 42, 4080, 4871, 4016, 4254],
 [143, 3968, 2559, 2033, 2134, 2174, 605, 143, 2375],
 [2522, 2314, 3728, 2029, 1579, 2393, 3471, 1061, 602, 965],
 [1658, 1567, 193, 1809, 3338, 1061, 602, 965],
 [1619, 134, 4482, 4622, 3273, 1123, 1850, 464, 3669, 4975],
 [4329, 1196, 3601],
 [445, 4186, 3902, 1677, 4016, 3199, 1220, 2643],
 [4095

In [17]:
#Lets take a look on the changes i.e- words vs vectors-
print(messages['title'][0])
print('===================')
print(onehot_repr[0])

House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It
[1734, 3968, 3661, 1973, 4080, 3769, 1682, 3804, 3129, 3901]


In [18]:
#Embedding Representation : Lets apply Padding (Pre/Post) to set/standardize sentence length -
#Lets apply Post-Padding - i.e- standardize the length of sentence and add zeros in short-length sentences after the sentence ends- 
from tensorflow.keras.preprocessing.sequence import pad_sequences
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[1734 3968 3661 ...    0    0    0]
 [1086 3601 2806 ...    0    0    0]
 [1206 2555 3668 ...    0    0    0]
 ...
 [4098 4462   11 ...    0    0    0]
 [2973 4254 1846 ...    0    0    0]
 [1529  487 1057 ...    0    0    0]]


In [19]:
print(embedded_docs[1])
print(embedded_docs[0])

[1086 3601 2806 4745 1311 1573 2643    0    0    0    0    0    0    0
    0    0    0    0    0    0]
[1734 3968 3661 1973 4080 3769 1682 3804 3129 3901    0    0    0    0
    0    0    0    0    0    0]


In [20]:
#Lets create an object for the algorithm -
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
model=Sequential()

In [21]:
#Lets Add an Layers and Features -
embedding_vector_features=40   #features representation - 40 features
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))           #LSTM Neural network layer with 100 input Neurons
model.add(Dense(1,activation='sigmoid'))   #for Binary output (Activation function = sigmoid, loss = binary_crossentropy)
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [22]:
#Lets see length -
len(embedded_docs),y.shape

(18285, (18285,))

In [23]:
#Lets convert List to array -
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)
print(X_final.shape,y_final.shape)

(18285, 20) (18285,)


In [24]:
#Lets split the data in train_test_split parts -
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [25]:
# Lets Train the model - you can also apply early stopping -
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 9s 30ms/step - loss: 0.3228 - accuracy: 0.8433 - val_loss: 0.2066 - val_accuracy: 0.9130
Epoch 2/10
192/192 [==============================] - 5s 26ms/step - loss: 0.1341 - accuracy: 0.9496 - val_loss: 0.2469 - val_accuracy: 0.9157
Epoch 3/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0860 - accuracy: 0.9682 - val_loss: 0.2827 - val_accuracy: 0.9122
Epoch 4/10
192/192 [==============================] - 5s 26ms/step - loss: 0.0566 - accuracy: 0.9813 - val_loss: 0.3348 - val_accuracy: 0.9120
Epoch 5/10
192/192 [==============================] - 5s 27ms/step - loss: 0.0335 - accuracy: 0.9890 - val_loss: 0.3400 - val_accuracy: 0.9037
Epoch 6/10
192/192 [==============================] - 4s 22ms/step - loss: 0.0250 - accuracy: 0.9927 - val_loss: 0.4095 - val_accuracy: 0.9085
Epoch 7/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0176 - accuracy: 0.9954 - val_loss: 0.4389 - val_accuracy: 0.9049

In [26]:
#Lets Predict the Y - axis values -
y_pred=model.predict(X_test)

189/189 [==============================] - 2s 7ms/step


In [27]:
#Lets consider if output value is less than 0.5 consider 0 and Else consider 1 - Because this is Binary Classification -
y_pred=np.where(y_pred > 0.5, 1,0)

In [28]:
#Lets Evaluate our Model -
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print('=============================================')
print('accuracy_score:',accuracy_score(y_test,y_pred))
print('==============================================')

[[3112  307]
 [ 241 2375]]
accuracy_score: 0.9091963545981773


# Thank You...